import {Food} from './app/shared/models/food';
import { Tag } from './app/shared/models/tag';

export const sample_foods: Food[] = [
  {
    id:'1',
    name: 'Pizza Pepperoni',
    cookTime: '10-20',
    price: 10,
    favorite: false,
    origins: ['italy'],
    imageUrl: 'assets/food-1.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'2',
    name: 'Meatball',
    price: 20,
    cookTime: '20-30',
    favorite: true,
    origins: ['persia', 'middle east', 'china'],
    imageUrl: 'assets/food-2.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id:'3',
    name: 'Hamburger',
    price: 5,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    imageUrl: 'assets/food-3.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id:'4',
    name: 'Fried Potatoes',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    imageUrl: 'assets/food-4.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id:'5',
    name: 'Chicken Soup',
    price: 11,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    imageUrl: 'assets/food-5.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id:'6',
    name: 'Vegetables Pizza',
    price: 9,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    imageUrl: 'assets/food-6.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'7',
    name: 'Sushi',
    price: 15,
    cookTime: '30-40',
    favorite: true,
    origins: ['japan'],
    imageUrl: 'assets/food-7.jpg',
    tags: ['SlowFood', 'Seafood', 'Dinner'],
  },
  {
    id:'8',
    name: 'Tacos',
    price: 8,
    cookTime: '20-25',
    favorite: false,
    origins: ['mexico'],
    imageUrl: 'assets/food-8.jpg',
    tags: ['FastFood', 'Mexican', 'Lunch'],
  },
  {
    id:'9',
    name: 'Pasta Carbonara',
    price: 12,
    cookTime: '15-20',
    favorite: true,
    origins: ['italy'],
    imageUrl: 'assets/food-9.jpg',
    tags: ['SlowFood', 'Pasta', 'Dinner'],
  },
  {
    id:'10',
    name: 'Cheeseburger',
    price: 7,
    cookTime: '10-15',
    favorite: false,
    origins: ['us'],
    imageUrl: 'assets/food-10.jpg',
    tags: ['FastFood', 'Hamburger', 'Lunch'],
  },
  {
    id: '11',
    name: 'Spaghetti Bolognese',
    price: 13,
    cookTime: '20-30',
    favorite: false,
    origins: ['italy'],
    imageUrl: 'assets/food-11.jpg',
    tags: ['SlowFood', 'Pasta', 'Dinner'],
  },
  {
    id: '12',
    name: 'Pad Thai',
    price: 10,
    cookTime: '15-25',
    favorite: true,
    origins: ['thailand'],
    imageUrl: 'assets/food-12.jpg',
    tags: ['FastFood', 'Thai', 'Lunch'],
  },
  {
    id: '13',
    name: 'Caesar Salad',
    price: 8,
    cookTime: '10-15',
    favorite: false,
    origins: ['mexico', 'us'],
    imageUrl: 'assets/food-13.jpg',
    tags: ['FastFood', 'Salad', 'Lunch'],
  },
  {
    id: '14',
    name: 'Sushi Roll',
    price: 15,
    cookTime: '25-35',
    favorite: true,
    origins: ['japan'],
    imageUrl: 'assets/food-14.jpg',
    tags: ['SlowFood', 'Sushi', 'Dinner'],
  },
  {
    id: '15',
    name: 'Chicken Tikka Masala',
    price: 12,
    cookTime: '30-40',
    favorite: false,
    origins: ['india', 'uk'],
    imageUrl: 'assets/food-15.jpg',
    tags: ['SlowFood', 'Indian', 'Dinner'],
  },
  {
    id: '16',
    name: 'Fish and Chips',
    price: 9,
    cookTime: '20-30',
    favorite: false,
    origins: ['uk'],
    imageUrl: 'assets/food-16.jpg',
    tags: ['FastFood', 'British', 'Lunch'],
  },
  {
    id: '17',
    name: 'Tiramisu',
    price: 7,
    cookTime: '10-20',
    favorite: true,
    origins: ['italy'],
    imageUrl: 'assets/food-17.jpg',
    tags: ['Dessert'],
  },
  {
    id: '18',
    name: 'Pho',
    price: 11,
    cookTime: '30-40',
    favorite: false,
    origins: ['vietnam'],
    imageUrl: 'assets/food-18.jpg',
    tags: ['SlowFood', 'Vietnamese', 'Lunch'],
  },
  {
    id: '19',
    name: 'Gyros',
    price: 8,
    cookTime: '15-20',
    favorite: true,
    origins: ['greece'],
    imageUrl: 'assets/food-19.jpg',
    tags: ['FastFood', 'Greek', 'Lunch'],
  },
  {
    id: '20',
    name: 'Ramen',
    price: 10,
    cookTime: '20-30',
    favorite: false,
    origins: ['japan'],
    imageUrl: 'assets/food-20.jpg',
    tags: ['FastFood', 'Japanese', 'Lunch'],
  },
  {
    id: '21',
    name: 'Beef Stroganoff',
    price: 14,
    cookTime: '30-40',
    favorite: false,
    origins: ['russia'],
    imageUrl: 'assets/food-21.jpg',
    tags: ['SlowFood', 'Beef', 'Dinner'],
  },
  {
    id: '22',
    name: 'Miso Soup',
    price: 6,
    cookTime: '10-15',
    favorite: true,
    origins: ['japan'],
    imageUrl: 'assets/food-22.jpg',
    tags: ['SlowFood', 'Soup', 'Japanese', 'Lunch'],
  },
  {
    id: '23',
    name: 'Peking Duck',
    price: 18,
    cookTime: '40-50',
    favorite: false,
    origins: ['china'],
    imageUrl: 'assets/food-23.jpg',
    tags: ['SlowFood', 'Duck', 'Chinese', 'Dinner'],
  },
  {
    id: '24',
    name: 'Tandoori Chicken',
    price: 12,
    cookTime: '30-40',
    favorite: true,
    origins: ['india'],
    imageUrl: 'assets/food-24.jpg',
    tags: ['SlowFood', 'Chicken', 'Indian', 'Dinner'],
  },
  {
    id: '25',
    name: 'Ratatouille',
    price: 10,
    cookTime: '30-40',
    favorite: false,
    origins: ['france'],
    imageUrl: 'assets/food-25.jpg',
    tags: ['SlowFood', 'Vegetarian', 'French', 'Dinner'],
  },
  {
    id: '26',
    name: 'Moussaka',
    price: 11,
    cookTime: '40-50',
    favorite: true,
    origins: ['greece'],
    imageUrl: 'assets/food-26.jpg',
    tags: ['SlowFood', 'Greek', 'Dinner'],
  },
  {
    id: '27',
    name: 'Philly Cheesesteak',
    price: 9,
    cookTime: '20-30',
    favorite: false,
    origins: ['us'],
    imageUrl: 'assets/food-27.jpg',
    tags: ['FastFood', 'American', 'Lunch'],
  },
  {
    id: '28',
    name: 'Schnitzel',
    price: 10,
    cookTime: '20-30',
    favorite: true,
    origins: ['austria'],
    imageUrl: 'assets/food-28.jpg',
    tags: ['FastFood', 'German', 'Lunch'],
  },
  {
    id: '29',
    name: 'Ceviche',
    price: 13,
    cookTime: '10-20',
    favorite: false,
    origins: ['peru'],
    imageUrl: 'assets/food-29.jpg',
    tags: ['FastFood', 'Seafood', 'Lunch'],
  },
  {
    id: '30',
    name: 'Goulash',
    price: 11,
    cookTime: '30-40',
    favorite: true,
    origins: ['hungary'],
    imageUrl: 'assets/food-30.jpg',
    tags: ['SlowFood', 'Beef', 'Hungarian', 'Dinner'],
  },
  {
    id: '31',
    name: 'Greek Salad',
    price: 9,
    cookTime: '10-15',
    favorite: false,
    origins: ['greece'],
    imageUrl: 'assets/food-31.jpg',
    tags: ['FastFood', 'Salad', 'Greek', 'Lunch'],
  },
  {
    id: '32',
    name: 'Cobb Salad',
    price: 10,
    cookTime: '10-15',
    favorite: true,
    origins: ['us'],
    imageUrl: 'assets/food-32.jpg',
    tags: ['FastFood', 'Salad', 'American', 'Lunch'],
  },
  {
    id: '33',
    name: 'Caesar Salad',
    price: 8,
    cookTime: '10-15',
    favorite: false,
    origins: ['mexico', 'us'],
    imageUrl: 'assets/food-33.jpg',
    tags: ['FastFood', 'Salad', 'Mexican', 'Lunch'],
  },
  {
    id: '34',
    name: 'Nicoise Salad',
    price: 12,
    cookTime: '10-15',
    favorite: true,
    origins: ['france'],
    imageUrl: 'assets/food-34.jpg',
    tags: ['FastFood', 'Salad', 'French', 'Lunch'],
  },
  {
    id: '35',
    name: 'Caprese Salad',
    price: 10,
    cookTime: '10-15',
    favorite: false,
    origins: ['italy'],
    imageUrl: 'assets/food-35.jpg',
    tags: ['FastFood', 'Salad', 'Italian', 'Lunch'],
  },
  {
    id: '37',
    name: 'Cheesecake',
    price: 8,
    cookTime: '30-40',
    favorite: false,
    origins: ['greece'],
    imageUrl: 'assets/food-37.jpg',
    tags: ['Dessert', 'Greek'],
  },
  {
    id: '38',
    name: 'Chocolate Cake',
    price: 6,
    cookTime: '20-30',
    favorite: true,
    origins: ['us'],
    imageUrl: 'assets/food-38.jpg',
    tags: ['Dessert', 'American'],
  },
  {
    id: '39',
    name: 'Baklava',
    price: 9,
    cookTime: '30-40',
    favorite: false,
    origins: ['turkey'],
    imageUrl: 'assets/food-39.jpg',
    tags: ['Dessert', 'Turkish'],
  },
  {
    id: '40',
    name: 'Apple Pie',
    price: 7,
    cookTime: '40-50',
    favorite: true,
    origins: ['us'],
    imageUrl: 'assets/food-40.jpg',
    tags: ['Dessert', 'American'],
  }

  

]

export const sample_tags: Tag[] = [
  { name: 'All', count: 39 },
  { name: 'FastFood', count: 15 },
  { name: 'Pizza', count: 2 },
  { name: 'Lunch', count: 17 },
  { name: 'SlowFood', count: 10 },
  { name: 'Hamburger', count: 4 },
  { name: 'Fry', count: 4 },
  { name: 'Soup', count: 4 },
  { name: 'Seafood', count: 2 },
  { name: 'Mexican', count: 3 },
  { name: 'Dinner', count: 12 },
  { name: 'Pasta', count: 5 },
  { name: 'Thai', count: 1 },
  { name: 'Salad', count: 6 },
  { name: 'Sushi', count: 3 },
  { name: 'Indian', count: 2 },
  { name: 'British', count: 1 },
  { name: 'Dessert', count: 7 },
  { name: 'Vietnamese', count: 1 },
  { name: 'Greek', count: 4 },
  { name: 'Japanese', count: 4 },
  { name: 'Beef', count: 3 },
  { name: 'Chicken', count: 4 },
  { name: 'Duck', count: 1 },
  { name: 'Vegetarian', count: 1 },
  { name: 'Italian', count: 4 },
  { name: 'French', count: 2 },
  { name: 'Turkish', count: 1 },
  { name: 'American', count: 5 },
  { name: 'German', count: 1 },
  { name: 'Chinese', count: 1 },
  { name: 'Hungarian', count: 1 },
];

export const sample_users: any[] = [
  {
    
    name: "John Doe",
    email: "john@gmail.com",
    password: "12345",
    address: "Toronto On",
    isAdmin: true,
  },
  {
    name: "Jane Doe",
    email: "Jane@gmail.com",
    password: "12345",
    address: "Shanghai",
    isAdmin: false,
  },
];

